# Generated by Django 5.0.6 on 2024-07-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_hr', '0004_performanceevaluation_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('evaluation_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField()),
            ],
        ),
    ]
