# Generated by Django 5.0.6 on 2024-07-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_hr', '0006_feature_delete_payrollevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evaluation_date', models.DateField()),
            ],
        ),
    ]
