# Generated by Django 5.0.6 on 2024-07-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_hr', '0008_payroll_delete_payrollevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='net_pay',
        ),
    ]
