# Generated by Django 5.0.6 on 2024-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_hr', '0010_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='employee_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
